export const ufcCourses = [
  "Administração – Diurno – Fortaleza",
  "Administração – Noturno – Fortaleza",
  "Administração Pública – modalidade a distância",
  "Agronomia – Fortaleza",
  "Análise e Desenvolvimento de Sistemas – Itapajé",
  "Arquitetura e Urbanismo – Fortaleza",
  "Biblioteconomia – Fortaleza",
  "Biotecnologia – Fortaleza",
  "Ciência da Computação – Crateús",
  "Ciência da Computação – Fortaleza",
  "Ciência da Computação – Quixadá",
  "Ciência da Computação – Russas",
  "Ciência de Dados – Fortaleza",
  "Ciência de Dados – Itapajé",
  "Ciências Ambientais – Fortaleza",
  "Ciências Atuariais – Fortaleza",
  "Ciências Biológicas  – Bacharelado e Licenciatura – Fortaleza",
  "Ciências Contábeis – Diurno – Fortaleza",
  "Ciências Contábeis – Noturno – Fortaleza",
  "Ciências Econômicas – Diurno – Fortaleza",
  "Ciências Econômicas – Noturno – Fortaleza",
  "Ciências Econômicas – Sobral",
  "Ciências Sociais – Bacharelado – Integral – Fortaleza",
  "Ciências Sociais – Licenciatura – Vespertino/Noturno – Fortaleza",
  "Cinema e Audiovisual – Fortaleza",
  "Comunicação Social – Publicidade e Propaganda – Fortaleza",
  "Dança – Bacharelado",
  "Dança – Licenciatura",
  "Design – Fortaleza",
  "Design – Moda – Fortaleza",
  "Design Digital – Quixadá",
  "Direito – Diurno e Noturno – Fortaleza",
  "Economia Doméstica – Fortaleza",
  "Economia Ecológica – Fortaleza",
  "Educação Física – Bacharelado e Licenciatura – Diurno – Fortaleza",
  "Educação Física – Bacharelado e Licenciatura – Noturno – Fortaleza",
  "Enfermagem – Fortaleza",
  "Engenharia Ambiental e Sanitária – Crateús",
  "Engenharia Ambiental e Sanitária – Fortaleza",
  "Engenharia Civil – Crateús",
  "Engenharia Civil – Fortaleza",
  "Engenharia Civil – Russas",
  "Engenharia da Computação – Sobral",
  "Engenharia de Alimentos – Fortaleza",
  "Engenharia de Computação – Fortaleza",
  "Engenharia de Computação – Quixadá",
  "Engenharia de Energias Renováveis – Fortaleza",
  "Engenharia de Minas – Crateús",
  "Engenharia de Pesca – Fortaleza",
  "Engenharia de Petróleo – Fortaleza",
  "Engenharia de Produção – Russas",
  "Engenharia de Produção – Fortaleza",
  "Engenharia de Software – Quixadá",
  "Engenharia de Software – Russas",
  "Engenharia de Telecomunicações – Fortaleza",
  "Engenharia Elétrica – Fortaleza",
  "Engenharia Elétrica – Sobral",
  "Engenharia Mecânica – Fortaleza",
  "Engenharia Mecânica – Russas",
  "Engenharia Metalúrgica – Fortaleza",
  "Engenharia Química – Fortaleza",
  "Estatística – Fortaleza",
  "Farmácia – Fortaleza",
  "Filosofia – Fortaleza",
  "Finanças – Fortaleza",
  "Finanças – Sobral",
  "Física – modalidade a distância",
  "Física – Bacharelado – Fortaleza",
  "Física – Licenciatura – Fortaleza",
  "Fisioterapia – Fortaleza",
  "Gastronomia – Fortaleza",
  "Geografia – Bacharelado e Licenciatura – Fortaleza",
  "Geologia – Fortaleza",
  "Gestão de Políticas Públicas – Fortaleza",
  "História – Fortaleza",
  "Jornalismo – Fortaleza",
  "Letras – Espanhol – Noturno – Fortaleza",
  "Letras – Inglês – Noturno – Fortaleza",
  "Letras – Libras – Fortaleza",
  "Letras – Língua Portuguesa e Língua Alemã e Respectivas Literaturas – Licenciatura",
  "Letras – Língua Portuguesa e Língua Espanhola e Respectivas Literaturas – Licenciatura",
  "Letras – Língua Portuguesa e Língua Francesa e Respectivas Literaturas – Licenciatura",
  "Letras – Língua Portuguesa e Língua Inglesa e Respectivas Literaturas – Licenciatura",
  "Letras – Língua Portuguesa e Língua Italiana e Respectivas Literaturas – Licenciatura",
  "Letras – Língua Portuguesa e Respectivas Literaturas – Licenciatura",
  "Letras Espanhol – modalidade a distância",
  "Letras Inglês – modalidade a distância",
  "Letras Português – modalidade a distância",
  "Licenciatura Intercultural Indígena das Etnias Pitaguary, Tapeba, Kanindé de Aratuba, Jenipapo-Kanindé e Anacé – LII PITAKAJÁ",
  "Licenciatura Intercultural Indígena Kuaba",
  "Matemática – Bacharelado – Fortaleza",
  "Matemática – Licenciatura – Fortaleza",
  "Matemática – modalidade a distância",
  "Medicina – Fortaleza",
  "Medicina – Sobral",
  "Música – Fortaleza",
  "Música – Sobral",
  "Oceanografia – Fortaleza",
  "Odontologia – Fortaleza",
  "Odontologia – Sobral",
  "Pedagogia – Diurno – Fortaleza",
  "Pedagogia – modalidade a distância",
  "Pedagogia – Noturno – Fortaleza",
  "Pedagogia – PARFOR",
  "Psicologia – Fortaleza",
  "Psicologia – Sobral",
  "Química – Bacharelado – Fortaleza",
  "Química – Licenciatura – Fortaleza",
  "Química – modalidade a distância",
  "Redes de Computadores – Quixadá",
  "Secretariado Executivo – Fortaleza",
  "Segurança da Informação – Itapajé",
  "Sistemas de Informação – Crateús",
  "Sistemas de Informação – Quixadá",
  "Sistemas e Mídias Digitais – Diurno – Fortaleza",
  "Sistemas e Mídias Digitais – Noturno – Fortaleza",
  "Teatro – Fortaleza",
  "Tecnologia em Gestão de Qualidade – Fortaleza",
  "Zootecnia – Fortaleza",
];
